DCP_TRANSMISSION_MAP_SCALING = 0.95
PRELIMINARY_NETWORK_DEPTH = 4
REFINEMENT_NETWORK_DEPTH = 4
DCT_CUTOFF_RATIO = 0.2
DCP_KERNEL_SIZE = 15
DCP_TRANSMISSION_PERCENTILE = 0.001
DCP_MIN_TRANSMISSION = 0.1
ATTENTION_SCALING = 0.05